import { useSession } from 'next-auth/react';
import Head from 'next/head';

export default function Home() {
  const {data: userData}  = useSession();

  console.log(userData)
  return (
    <div className='h-screen w-screen justify-center items-center flex m-auto'>
      <Head>
        <title>Sample NextJs Practice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      
        
    </div>
  )
}
