import Head from 'next/head';
import { signInWithPopup, onAuthStateChanged,signOut } from "firebase/auth";
import {auth, provider} from '../firebase';
import {useEffect, useState} from 'react';

export default function Home() {
  const [userData, setUserData] = useState(null);

  const googleSignIn = () => {
  signInWithPopup(auth, provider)
  }

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, currentUser => {
      setUserData(currentUser);
      console.log(userData)
    })
    return () => {
      unsubscribe();
    }
  }, [])

  // useEffect(() => {console.log(userData)}, [userData])

  return (
    <div className='h-screen w-screen justify-center items-center flex m-auto'>
      <Head>
        <title>Sample NextJs Practice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='space-y-3 flex flex-col'>
        <button onClick={googleSignIn} className='rounded-lg hover:bg-rose-400 bg-rose-500 text-white text-lg p-4'>Sign In With Google</button>
          
          {userData && (
            <div>
              <button onClick={() => signOut(auth)} className='w-full rounded-lg hover:opacity-80 bg-gradient-to-r from-cyan-300 to-orange-300 text-white text-lg p-4'>Sign Out</button>
              <h1 className='font-sans text-2xl font-semibold mb-4 text-blue-500/40'>{userData.displayName.split(1,10)}...</h1>
              <p className='text-xl text-red-400'>{userData.email}</p>
            </div>
          )}
        </div>
    </div>
  )
}
